### ISSUE TITLE
lint 时报错 redundant dependency

### ISSUE THREAD

**Issue by afc163** [react-component/rc-tools#10]
```
🎯   banner-anim@0.2.7 git:❨master❩ tnpm run lint

> rc-banner-anim@0.2.7 lint /Users/afc163/Projects/banner-anim
> rc-tools run lint


/Users/afc163/Projects/banner-anim/node_modules/orchestrator/index.js:153
			throw err;
			^
redundant dependency in dependencies of package.json: style-utils
```

### 重现步骤

1. `git clone https://github.com/react-component/banner-anim && cd banner-anim`
2. `npm install`
3. 删除 https://github.com/react-component/banner-anim/blob/8721afddcca319d2206b86fe80f91a3cb04ea3d1/src/BannerAnim.jsx#L11-L12 这两行没有实际作用的代码。
4. `npm run lint`

**Comment by warmhug** [comment]
多余的依赖，https://github.com/react-component/banner-anim/blob/8721afddcca319d2206b86fe80f91a3cb04ea3d1/package.json#L53 这里删掉应该ok ？
![image](https://cloud.githubusercontent.com/assets/2011119/15828137/bd735b38-2c40-11e6-813e-55bcbd483ed6.png)

**Comment by afc163** [comment]
https://github.com/react-component/banner-anim/blob/8721afddcca319d2206b86fe80f91a3cb04ea3d1/src/Element.jsx#L14

有依赖的。

**Comment by superRaytin** [comment]
增加此依赖，也会报这个错：

![image](https://cloud.githubusercontent.com/assets/2723376/15885918/b5c6fd70-2d8c-11e6-8a5b-31b21c2e4602.png)
