### ISSUE TITLE
文件名大小写错了

### ISSUE THREAD

**Issue by 285858315** [react-component/rc-tools#27]
https://github.com/react-component/rc-tools/blob/master/lib/postcssConfig.js#L3

**Comment by paranoidjk** [comment]
来个 PR 帮忙修复？

**Comment by paranoidjk** [comment]
https://github.com/react-component/rc-tools/commit/ded1b32b217a3256975ac229ca9e9dda718278e1

**Comment by paranoidjk** [comment]
@yiminghe mac 的文件名大小写不敏感，但linux是区分的，不懂这里这样写的原因是啥？

**Comment by yiminghe** [comment]
手误，已经改好了啊

**Comment by paranoidjk** [comment]
@yiminghe 不是....是我修复了...然后你又给改回来了...

**Comment by paranoidjk** [comment]
`git config core.ignorecase false`
