### ISSUE TITLE
rc-tools 可否暴露一些配置项给开发者

### ISSUE THREAD

**Issue by liaobin312716** [react-component/rc-tools#4]
hi , rc-tools 是基于webpack 的吧。那是否可以暴露一些配置项给开发者，比如，我想自定义打包 rc-calendar , 然后再使用其他的库， 可能会有些资源复用的，比如React, classnames 我希望不打包进来，而是保持 require('react') ？

还有就是希望生成的文件，支持 umd ，应该怎么打包？？

**Comment by yiminghe** [comment]
这个是关注组件开发，不涉及打包及项目部署，项目开发请使用 antd-init
