### ISSUE TITLE
rc-tools 如何创建一个组件？ 

### ISSUE THREAD

**Issue by ThaddeusJiang** [react-component/rc-tools#50]
rc-tools 有提供 `init` 方法吗？

具体用法没看懂，能在 README 中写一下吗？

**Comment by yesmeck** [comment]
rc-tools init 目前没有被很好的维护，不建议使用。

**Comment by allan2coder** [comment]
@yesmeck  有类似的推荐吗？

**Comment by yesmeck** [comment]
自己写组件用 storybook 就可以了。

**Comment by ThaddeusJiang** [comment]
@allan2coder 我最近发现一个很好用的 CLI，推荐给你。
https://github.com/transitive-bullshit/create-react-library

**Comment by ThaddeusJiang** [comment]
我试用了一下蛮好用，基本的配置都有。

👇这个项目就是用的这个 CLI。
https://github.com/ThaddeusJiang/react-mobile-wrapper

**Comment by allan2coder** [comment]
@ThaddeusJiang  感谢
