### ISSUE TITLE
添加macaca-client选项，给用户更多优秀的选择

### ISSUE THREAD

**Issue by xudafeng** [react-component/rc-tools#6]
@yiminghe @sorrycc @afc163

**Comment by yiminghe** [comment]
e， pr 下，怎么支持啊

**Comment by xudafeng** [comment]
🆗 ,  "phantomjs-prebuilt" 这个依赖做了什么,https://github.com/react-component/rc-tools/blob/master/package.json#L93

**Comment by yiminghe** [comment]
我们其实是想搞个完全不依赖渲染引擎的，比如 jsdom 这种 https://github.com/ant-tool/atool-test/issues/15

**Comment by xudafeng** [comment]
@yiminghe 说说好处啊
