### ISSUE TITLE
No way to change Webpack config

### ISSUE THREAD

**Issue by matthewgertner** [react-component/rc-tools#9]
I wanted to use Enzyme with my `rc-tools` powered component, but it requires some modifications to the Webpack config so that it ignores some conditional `require`s. I couldn't see anyway to override the default Webpack settings though. Am I missing something?

**Comment by paranoidjk** [comment]
right now we do not have time to refactor rc-tools, you can config jest && enzyme in your own project, see https://github.com/react-component/slider/commit/9c6da294d4b453a7091d61b211cd95936243e641
